// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smvathnyxjcoaovnaqij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtdmF0aG55eGpjb2Fvdm5hcWlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTI4MDQsImV4cCI6MjA3MTg4ODgwNH0.Rxvy-aW_42yb3_ecex8Damsa6mwStzeLL3mO3tyXLYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});